### ISSUE TITLE
Think of a way to avoid instantiating Position class

### ISSUE THREAD

**Issue by javierfernandes** [ProyectoFinal2015/wollok#30]
Currently to use wollok game you need to instantiate the Position class.

``` xtend
new Position(3, 3).drawCharacterWithReferences(granjero, #["oro", "cultivos"])
```

We want to avoid showing classes in the first part of the OOP learning-path.
So we should think of a way to avoid it.
It could be with a new feature in wollok language itself like extension methods or literals.

Example using a literal

``` xtend
(3 : 3).drawCharacterWithReferences(granjero, #["oro", "cultivos"])
```

Although I don't like to couple the language syntax with wollok game.
Another option more object-based without any feature

``` xtend
game.at(3, 3).drawCharacterWithReferences(granjero, #["oro", "cultivos"])
```

**Comment by PalumboN** [comment]
I agree. The last version is ok for me!

**Comment by javierfernandes** [comment]
Moving to https://github.com/uqbar-project/wollok/issues/478
